const resobj = [
    // {
    //     id:"1234",
    //     name: "Cafe Amudham",
    //     costfortwo: "₹400 for two",
    //     cuisines: ["South Indian","Snacks"],
    //     avgRating: 4.6,
    // },
    // {
    //     id:"1235",
    //     name: "Meghna Foods",
    //     costfortwo: "₹350 for two",
    //     cuisines: ["North Indian","Snacks"],
    //     avgRating: 4.5,
    // },
    // {
    //     id:"1236",
    //     name: "Fasoos Foods",
    //     costfortwo: "₹350 for two",
    //     cuisines: ["North Indian","Snacks"],
    //     avgRating: 3.5,
    // },
    // {
    //     id:"1237",
    //     name: "Empire Foods",
    //     costfortwo: "₹250 for two",
    //     cuisines: ["North Indian","Snacks"],
    //     avgRating: 3.9,
    // },
    // {
    //     id:"1238",
    //     name: "Windys Foods",
    //     costfortwo: "₹100 for two",
    //     cuisines: ["North Indian","Snacks"],
    //     avgRating: 4.9,
    // },
    // {
    //     id:"1239",
    //     name: "Ganesh Foods",
    //     costfortwo: "₹150 for two",
    //     cuisines: ["South Indian","Snacks"],
    //     avgRating: 3.8,
    // },
    // {
    //     id:"1240",
    //     name: "Udupi Foods",
    //     costfortwo: "₹300 for two",
    //     cuisines: ["North Indian","Snacks"],
    //     avgRating: 4.2,
    // },
    // {
    //     id:"1241",
    //     name: "Khan Chacha Foods",
    //     costfortwo: "₹400 for two",
    //     cuisines: ["North Indian","Biryani"],
    //     avgRating: 4.7,
    // },
    // {
    //     id:"1242",
    //     name: "Meghna Foods",
    //     costfortwo: "₹350 for two",
    //     cuisines: ["North Indian","Snacks"],
    //     avgRating: 3.6,
    // },
    // {
    //     id:"1243",
    //     name: "Meghna Foods",
    //     costfortwo: "₹350 for two",
    //     cuisines: ["North Indian","Snacks"],
    //     avgRating: 4.0,
    // },
    // {
    //     id:"1244",
    //     name: "Meghna Foods",
    //     costfortwo: "₹350 for two",
    //     cuisines: ["North Indian","Snacks"],
    //     avgRating: 3.7,
    // },
    // {
    //     id:"1245",
    //     name: "Meghna Foods",
    //     costfortwo: "₹350 for two",
    //     cuisines: ["North Indian","Snacks"],
    //     avgRating: 4.1,
    // },
    // {
    //     id:"1246",
    //     name: "McDownloads Foods",
    //     costfortwo: "₹350 for two",
    //     cuisines: ["North Indian","Snacks"],
    //     avgRating: 3.1,
    // },
    // {
    //     id:"1247",
    //     name: "Meghna Foods",
    //     costfortwo: "₹350 for two",
    //     cuisines: ["North Indian","Snacks"],
    //     avgRating: 3.2,
    // },
    // {
    //     id:"1248",
    //     name: "Meghna Foods",
    //     costfortwo: "₹350 for two",
    //     cuisines: ["North Indian","Snacks"],
    //     avgRating: 3.3,
    // },
];
export default resobj;